using Microsoft.Extensions.Logging;

using Prdb.Fab.Core.Sync;
using Prdb.Fab.Infrastructure.Persistence;

namespace Prdb.Fab.Infrastructure.Sync;

/// <summary>
/// ADR 0064's generated bytes: a sheet and its WebVTT under the data directory
/// at <c>publications/&lt;two hex&gt;/&lt;id&gt;</c>, waiting to be sent.
/// </summary>
/// <remarks>
/// <para>
/// The same seam <see cref="PreviewAssetStore"/> draws — the bytes, and nothing
/// about the rows — and written the same way, because a pair is written the
/// same way whichever direction it is going: each half under a temporary name
/// and renamed, and the row's commit afterwards. What differs is which way the
/// commit faces. There, the version on the file name is what stops two halves
/// from being from different fetches; here the row's own id is the version, so
/// a crash between the halves leaves files that belong to a row still saying
/// <see cref="PreviewPublicationState.Intended"/> — and the next attempt
/// overwrites them.
/// </para>
/// <para>
/// <strong>Nothing here is in the Backup</strong>, and this is the easy case of
/// ADR 0009's test rather than the interesting one: these bytes were made
/// locally from a file the Library still holds, so they can be made again from
/// the same file and the same output version.
/// </para>
/// </remarks>
public sealed class PublicationStore(FabDatabaseLocation location, ILogger<PublicationStore> logger)
{
    private readonly string root = Path.Combine(location.DataDirectory, PublicationFile.Directory);

    /// <summary>Where this publication's sheet is, whether or not it is there.</summary>
    public string SheetPathOf(Guid publicationId) =>
        Path.Combine(location.DataDirectory, PublicationFile.SheetPathOf(publicationId));

    /// <summary>Where this publication's WebVTT is.</summary>
    public string VttPathOf(Guid publicationId) =>
        Path.Combine(location.DataDirectory, PublicationFile.VttPathOf(publicationId));

    /// <summary>Whether both halves of this publication are on disk.</summary>
    public bool Holds(Guid publicationId) =>
        File.Exists(SheetPathOf(publicationId)) && File.Exists(VttPathOf(publicationId));

    /// <summary>
    /// Writes both halves, the sheet first.
    /// </summary>
    /// <remarks>
    /// Neither rename is the commit — the row's state is — so the order between
    /// them decides nothing. They are written together here so that no caller
    /// has the chance to write one and forget the other.
    /// </remarks>
    public async Task WritePairAsync(
        Guid publicationId,
        byte[] sheet,
        byte[] vtt,
        CancellationToken cancellationToken)
    {
        await WriteAsync(SheetPathOf(publicationId), sheet, cancellationToken);
        await WriteAsync(VttPathOf(publicationId), vtt, cancellationToken);
    }

    /// <summary>Opens one half for reading, or null where there is none.</summary>
    public Stream? OpenSheet(Guid publicationId) => Open(SheetPathOf(publicationId));

    public Stream? OpenVtt(Guid publicationId) => Open(VttPathOf(publicationId));

    /// <summary>Drops both halves of one publication. Silent where there are none.</summary>
    public void Delete(Guid publicationId)
    {
        Remove(SheetPathOf(publicationId));
        Remove(VttPathOf(publicationId));
    }

    /// <summary>
    /// Deletes every file under the directory that <paramref name="claimed"/>
    /// does not name, and every half-written one whatever it is called.
    /// </summary>
    /// <remarks>
    /// <para>
    /// What reclaims the bytes of a decode that was cancelled, timed out or was
    /// interrupted by a restart. There is no state to reconcile: a publication
    /// that still owes a decode owns no finished bytes, and one that has been
    /// sent or dropped owns none either, so anything on disk that no waiting row
    /// claims is simply leftover.
    /// </para>
    /// <para>
    /// A part file is swept whatever its age, because nothing writes one except
    /// a write in progress and the writer of this pass is the only writer there
    /// is: the generating routine holds the Bulk lane while it decodes, so a
    /// part file seen from inside it is by construction not being written.
    /// </para>
    /// </remarks>
    public int Reclaim(IReadOnlySet<Guid> claimed)
    {
        if (!Directory.Exists(root))
        {
            return 0;
        }

        var reclaimed = 0;

        foreach (var file in Files())
        {
            var name = Path.GetFileName(file);

            if (name.EndsWith(PublicationFile.PartSuffix, StringComparison.Ordinal))
            {
                Remove(file);
                reclaimed++;
                continue;
            }

            if (PublicationFile.Read(name) is { } publicationId && !claimed.Contains(publicationId))
            {
                Remove(file);
                reclaimed++;
            }
        }

        return reclaimed;
    }

    /// <summary>What the directory weighs, which is what a surface reports.</summary>
    public long Weight()
    {
        if (!Directory.Exists(root))
        {
            return 0;
        }

        var bytes = 0L;

        foreach (var file in Files())
        {
            try
            {
                bytes += new FileInfo(file).Length;
            }
            catch (IOException)
            {
                // Swept out from under the walk. It weighs nothing now.
            }
        }

        return bytes;
    }

    private IEnumerable<string> Files()
    {
        IEnumerator<string> walk;

        try
        {
            walk = Directory.EnumerateFiles(root, "*", SearchOption.AllDirectories).GetEnumerator();
        }
        catch (DirectoryNotFoundException)
        {
            yield break;
        }

        using (walk)
        {
            while (true)
            {
                try
                {
                    if (!walk.MoveNext())
                    {
                        yield break;
                    }
                }
                catch (Exception failed) when (failed is IOException or UnauthorizedAccessException)
                {
                    logger.LogWarning(failed, "Could not walk the generated preview directory.");
                    yield break;
                }

                yield return walk.Current;
            }
        }
    }

    private static async Task WriteAsync(string path, byte[] bytes, CancellationToken cancellationToken)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        // Beside the file rather than in the system temporary directory, for
        // PreviewAssetStore's reason: ADR 0034 mounts /data from the host and
        // the container's own /tmp is not on it, so only a rename within this
        // directory is atomic.
        var writing = $"{path}.{Guid.NewGuid():n}{PublicationFile.PartSuffix}";

        try
        {
            await File.WriteAllBytesAsync(writing, bytes, cancellationToken);

            File.Move(writing, path, overwrite: true);
        }
        catch
        {
            Forget(writing);
            throw;
        }
    }

    private static Stream? Open(string path)
    {
        try
        {
            return File.OpenRead(path);
        }
        catch (FileNotFoundException)
        {
            return null;
        }
        catch (DirectoryNotFoundException)
        {
            return null;
        }
    }

    private void Remove(string path)
    {
        try
        {
            File.Delete(path);
        }
        catch (Exception failed) when (failed is IOException or UnauthorizedAccessException)
        {
            logger.LogWarning(failed, "Could not remove a generated preview's bytes.");
        }
    }

    private static void Forget(string path)
    {
        try
        {
            File.Delete(path);
        }
        catch (Exception failed) when (failed is IOException or UnauthorizedAccessException)
        {
            // The half-written file of a write that threw. The sweep takes it
            // by its suffix on the next pass.
        }
    }
}
