using System.Text;

using Prdb.Fab.Core.Sync;

using Xunit;

namespace Prdb.Fab.Core.Tests.Sync;

/// <summary>
/// ADR 0061's WebVTT reader: what it accepts, what it refuses whole, and the
/// one thing it never does.
/// </summary>
public sealed class SpriteTimelineTests
{
    private static readonly (int Width, int Height) Sheet = (3200, 1800);

    /// <summary>
    /// The ordinary case, as a thumbnail track is actually written: a signature,
    /// blank-line-separated cues, and a payload that is a file name with an
    /// <c>xywh</c> fragment.
    /// </summary>
    [Fact]
    public void A_thumbnail_track_reads_as_its_tiles()
    {
        var timeline = Read("""
            WEBVTT

            00:00:00.000 --> 00:00:10.000
            sprite.jpg#xywh=0,0,320,180

            00:00:10.000 --> 00:00:20.000
            sprite.jpg#xywh=320,0,320,180

            00:00:20.000 --> 00:00:30.000
            sprite.jpg#xywh=640,0,320,180
            """);

        Assert.True(timeline.Usable);
        Assert.Equal(3, timeline.Tiles.Count);

        Assert.Equal(TimeSpan.FromSeconds(10), timeline.Tiles[1].Start);
        Assert.Equal(TimeSpan.FromSeconds(20), timeline.Tiles[1].End);
        Assert.Equal(320, timeline.Tiles[1].X);
        Assert.Equal(0, timeline.Tiles[1].Y);
        Assert.Equal(320, timeline.Tiles[1].Width);
        Assert.Equal(180, timeline.Tiles[1].Height);
    }

    /// <summary>
    /// Cue identifiers, <c>NOTE</c> blocks and cue settings are all ordinary
    /// WebVTT and none of them says which tile is when.
    /// </summary>
    [Fact]
    public void Identifiers_notes_and_cue_settings_are_skipped()
    {
        var timeline = Read("""
            WEBVTT - a thumbnail track

            NOTE
            Generated by something.

            tile-1
            00:00.000 --> 00:10.000 align:start line:0
            sprite.jpg#xywh=0,0,320,180
            """);

        Assert.True(timeline.Usable);

        var tile = Assert.Single(timeline.Tiles);

        // And the short form of a timestamp — mm:ss.mmm — is the same time as
        // the long one.
        Assert.Equal(TimeSpan.Zero, tile.Start);
        Assert.Equal(TimeSpan.FromSeconds(10), tile.End);
    }

    /// <summary>
    /// The property the parser exists to have: what a cue names before the
    /// fragment is never read, so there is no path from a cue to a request.
    /// Three ways of writing something a naive reader would go and get, and all
    /// three produce the same tile.
    /// </summary>
    [Theory]
    [InlineData("https://elsewhere.invalid/steal#xywh=0,0,320,180")]
    [InlineData("../../../../etc/passwd#xywh=0,0,320,180")]
    [InlineData("data:text/html;base64,PHNjcmlwdD4=#xywh=0,0,320,180")]
    public void A_cue_payload_is_a_rectangle_and_never_an_address(string payload)
    {
        var timeline = Read($"""
            WEBVTT

            00:00:00.000 --> 00:00:10.000
            {payload}
            """);

        Assert.True(timeline.Usable);

        var tile = Assert.Single(timeline.Tiles);

        Assert.Equal(0, tile.X);
        Assert.Equal(320, tile.Width);
    }

    /// <summary>
    /// A rectangle outside the sheet is the whole file's problem rather than
    /// that cue's: drawing what is there and silently skipping the rest would
    /// put a person's scrub on the wrong second with nothing saying so.
    /// </summary>
    [Fact]
    public void A_rectangle_outside_the_sheet_makes_the_whole_timeline_unusable()
    {
        var timeline = Read("""
            WEBVTT

            00:00:00.000 --> 00:00:10.000
            sprite.jpg#xywh=0,0,320,180

            00:00:10.000 --> 00:00:20.000
            sprite.jpg#xywh=3100,1700,320,180
            """);

        Assert.False(timeline.Usable);
        Assert.Empty(timeline.Tiles);
    }

    [Fact]
    public void Cues_out_of_order_are_refused()
    {
        var timeline = Read("""
            WEBVTT

            00:00:20.000 --> 00:00:30.000
            sprite.jpg#xywh=0,0,320,180

            00:00:00.000 --> 00:00:10.000
            sprite.jpg#xywh=320,0,320,180
            """);

        Assert.False(timeline.Usable);
    }

    [Fact]
    public void A_cue_that_ends_before_it_starts_is_refused()
    {
        var timeline = Read("""
            WEBVTT

            00:00:20.000 --> 00:00:10.000
            sprite.jpg#xywh=0,0,320,180
            """);

        Assert.False(timeline.Usable);
    }

    [Fact]
    public void A_file_without_the_signature_is_refused()
    {
        var timeline = Read("""
            NOTVTT

            00:00:00.000 --> 00:00:10.000
            sprite.jpg#xywh=0,0,320,180
            """);

        Assert.False(timeline.Usable);
    }

    [Fact]
    public void A_file_with_no_cues_at_all_is_refused()
    {
        Assert.False(Read("WEBVTT\n\nNOTE nothing here\n").Usable);
    }

    [Fact]
    public void A_cue_whose_payload_is_not_a_rectangle_is_refused()
    {
        var timeline = Read("""
            WEBVTT

            00:00:00.000 --> 00:00:10.000
            Some subtitle text, which is what WebVTT is usually for.
            """);

        Assert.False(timeline.Usable);
    }

    /// <summary>
    /// The bound, and it is the file's whole problem rather than a truncation:
    /// a sheet cut into more tiles than the contract admits is not one this
    /// build knows the shape of.
    /// </summary>
    [Fact]
    public void More_cues_than_the_contract_admits_are_refused()
    {
        var vtt = new StringBuilder("WEBVTT\n");

        for (var index = 0; index <= UserPreviewContract.Tiles; index++)
        {
            vtt.Append($"\n00:{index / 60:D2}:{index % 60:D2}.000 --> 00:{(index + 1) / 60:D2}:{(index + 1) % 60:D2}.000\n")
                .Append("sprite.jpg#xywh=0,0,320,180\n");
        }

        Assert.False(Read(vtt.ToString()).Usable);
    }

    /// <summary>
    /// Bytes that are not UTF-8 are not a WebVTT. Replacing them instead would
    /// let a file parse as an empty timeline, which is a different failure with
    /// the same symptom.
    /// </summary>
    [Fact]
    public void Bytes_that_are_not_utf8_are_refused()
    {
        byte[] vtt = [0xFF, 0xFE, 0x00, 0x57, 0x00, 0x45];

        Assert.False(SpriteTimeline.Read(vtt, Sheet, UserPreviewContract.Tiles).Usable);
    }

    /// <summary>A byte-order mark is allowed and is not part of the signature.</summary>
    [Fact]
    public void A_byte_order_mark_is_allowed()
    {
        var vtt = new byte[] { 0xEF, 0xBB, 0xBF }
            .Concat(Encoding.UTF8.GetBytes("WEBVTT\n\n00:00.000 --> 00:10.000\nsprite.jpg#xywh=0,0,320,180\n"))
            .ToArray();

        Assert.True(SpriteTimeline.Read(vtt, Sheet, UserPreviewContract.Tiles).Usable);
    }

    /// <summary>A sheet with no dimensions cannot validate anything.</summary>
    [Fact]
    public void A_sheet_with_no_dimensions_makes_every_timeline_unusable()
    {
        var vtt = Encoding.UTF8.GetBytes("WEBVTT\n\n00:00.000 --> 00:10.000\nsprite.jpg#xywh=0,0,320,180\n");

        Assert.False(SpriteTimeline.Read(vtt, (0, 0), UserPreviewContract.Tiles).Usable);
    }

    private static SpriteTimelineResult Read(string vtt) =>
        SpriteTimeline.Read(Encoding.UTF8.GetBytes(vtt), Sheet, UserPreviewContract.Tiles);
}
