// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prdb.Fab.Infrastructure.Persistence;

#nullable disable

namespace Prdb.Fab.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FabDbContext))]
    [Migration("20260829193025_WantedAutomation")]
    partial class WantedAutomation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.ArrivingFileCandidateRow", b =>
                {
                    b.Property<Guid>("ArrivingFileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.HasKey("ArrivingFileId", "VideoId");

                    b.HasIndex("VideoId");

                    b.ToTable("arriving_file_candidate", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.Exported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.ArrivingFileRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArrivedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("DerivedReleaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DownloadId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IndexerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntendedPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnDisk")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProbeError")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProbeOutcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RuntimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoCodec")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VideoId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Reason")
                        .HasFilter("\"Reason\" IS NOT NULL");

                    b.HasIndex("State");

                    b.HasIndex("VideoId");

                    b.HasIndex("DownloadId", "SourcePath")
                        .IsUnique();

                    b.ToTable("arriving_file", null, t =>
                        {
                            t.HasCheckConstraint("CK_arriving_file_reason", "\"Reason\" IS NULL OR \"Reason\" IN ('IdenticalFile','UnreadableQuality','Unidentified','Duplicate','EntryMissing')");

                            t.HasCheckConstraint("CK_arriving_file_state", "\"State\" IN ('AwaitingIdentification','AwaitingFiling','Filing','Filed')");
                        });

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.Exported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.AutomationRuleIndexerRow", b =>
                {
                    b.Property<Guid>("AutomationRuleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IndexerId")
                        .HasColumnType("TEXT");

                    b.HasKey("AutomationRuleId", "IndexerId");

                    b.HasIndex("IndexerId");

                    b.ToTable("automation_rule_indexer", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.Exported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.AutomationRuleRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MaximumSize")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MinimumSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("automation_rule", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.Exported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.CatalogueActorRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrdbId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrdbId")
                        .IsUnique();

                    b.ToTable("catalogue_actor", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.NotExported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.CatalogueImageRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cached")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("FoundDead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastServedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid>("PrdbId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Cached")
                        .HasFilter("\"Cached\" = 0");

                    b.HasIndex("LastServedAt");

                    b.HasIndex("PrdbId")
                        .IsUnique();

                    b.HasIndex("VideoId", "Position", "PrdbId");

                    b.ToTable("catalogue_image", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.NotExported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.CatalogueSiteRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Network")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrdbId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StillOffered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrdbId")
                        .IsUnique();

                    b.ToTable("catalogue_site", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.NotExported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.CatalogueVideoActorRow", b =>
                {
                    b.Property<long>("VideoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ActorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VideoId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("catalogue_video_actor", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.NotExported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.CatalogueVideoPreNameRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalisedPreName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SearchedBackwards")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<long>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SearchedBackwards");

                    b.HasIndex("VideoId", "PreName")
                        .IsUnique();

                    b.ToTable("catalogue_video_pre_name", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.NotExported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.CatalogueVideoRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationFileCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DurationSpreadMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastReadAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalisedTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrdbId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TitleSearchedBackwards")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrdbId")
                        .IsUnique();

                    b.HasIndex("SiteId");

                    b.HasIndex("TitleSearchedBackwards");

                    b.HasIndex("CreatedAtUtc", "Id");

                    b.ToTable("catalogue_video", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.NotExported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.ConfirmedAssignmentRow", b =>
                {
                    b.Property<string>("OsHash")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArrivalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrdbAnswer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RuntimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoCodec")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("OsHash", "VideoId", "UserHash");

                    b.ToTable("confirmed_assignment", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountStamped")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.Exported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.DownloadOriginRuleRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AutomationRuleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DownloadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AutomationRuleId");

                    b.HasIndex("DownloadId");

                    b.ToTable("download_origin_rule", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.Exported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.DownloadRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cause")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveAbsences")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DerivedReleaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FailMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IndexerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSabnzbdStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("NzoId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OriginIsPerson")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OutstandingSince")
                        .HasColumnType("TEXT");

                    b.Property<string>("StageLog")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Storage")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TidiedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.HasIndex("State", "CreatedAt");

                    b.HasIndex("VideoId", "IndexerId", "DerivedReleaseId")
                        .IsUnique();

                    b.ToTable("download", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.Exported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.FavouriteActorRow", b =>
                {
                    b.Property<long>("ActorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SinceAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ActorId");

                    b.ToTable("favourite_actor", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountScoped")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.NotExported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.FavouriteSiteRow", b =>
                {
                    b.Property<long>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SinceAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SiteId");

                    b.ToTable("favourite_site", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountScoped")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.NotExported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.FeedCursorRow", b =>
                {
                    b.Property<string>("Feed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cursor")
                        .HasColumnType("TEXT");

                    b.HasKey("Feed");

                    b.ToTable("feed_cursor", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "PerRow")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.NotExported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.GateAdmissionRow", b =>
                {
                    b.Property<string>("Gate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.HasKey("Gate", "Confidence");

                    b.ToTable("gate_admission", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.Exported);

                    b.HasData(
                        new
                        {
                            Gate = "BeforeDownload",
                            Confidence = "Exact"
                        },
                        new
                        {
                            Gate = "BeforeDownload",
                            Confidence = "Strong"
                        },
                        new
                        {
                            Gate = "BeforeDownload",
                            Confidence = "Probable"
                        },
                        new
                        {
                            Gate = "AfterDownload",
                            Confidence = "Exact"
                        },
                        new
                        {
                            Gate = "AfterDownload",
                            Confidence = "Strong"
                        });
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.IdentificationOutcomeRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.ToTable("identification_outcome", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.NotExported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.IndexerRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DailyQueryBudget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1000);

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastVerdict")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("indexer", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.Exported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.IndexerWalkStateRow", b =>
                {
                    b.Property<Guid>("IndexerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BootstrapCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CapsCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapsTree")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CatchUpCause")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CatchUpFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CatchUpTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MissingCategoryNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QueriesSpentToday")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("QueryDay")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedCategoryIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResumePage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SweepQueriesSpentToday")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WatermarkPostDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("WatermarkReleaseId")
                        .HasColumnType("TEXT");

                    b.HasKey("IndexerId");

                    b.ToTable("indexer_walk_state", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.NotExported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.InstallationRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutomaticDownloadCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(20);

                    b.Property<bool>("DeleteLeftovers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IndexersSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LibraryRoot")
                        .HasColumnType("TEXT");

                    b.Property<string>("OnboardingStep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathMappingFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathMappingTo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PlanShortSince")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrdbApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrdbUserHash")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReportConfirmedAssignments")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReportFulfilments")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryBudget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(3);

                    b.Property<string>("SabnzbdApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SabnzbdCategory")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SabnzbdSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SabnzbdUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("installation", null, t =>
                        {
                            t.HasCheckConstraint("CK_installation_one_row", "\"Id\" = 1");
                        });

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.Exported);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutomaticDownloadCap = 20,
                            DeleteLeftovers = false,
                            IndexersSkipped = false,
                            OnboardingStep = "Password",
                            ReportConfirmedAssignments = true,
                            ReportFulfilments = true,
                            RetryBudget = 3,
                            SabnzbdSkipped = false
                        });
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.LibraryEntryRow", b =>
                {
                    b.Property<Guid>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FiledAt")
                        .HasColumnType("TEXT");

                    b.HasKey("VideoId");

                    b.ToTable("library_entry", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.Exported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.OperationLogEntryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Act")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplacedPath")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DownloadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeftoverNamesJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LibraryEntryVideoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathAfter")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathBefore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VideoFileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VideoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("operation_log_entry", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.Exported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.ReleaseCandidateRow", b =>
                {
                    b.Property<long>("ReleaseId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReleaseId", "VideoId");

                    b.HasIndex("ReleaseId");

                    b.HasIndex("VideoId");

                    b.ToTable("release_candidate", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.NotExported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.ReleaseNotDownloadedRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.ToTable("release_not_downloaded", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.NotExported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.ReleaseRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AutomationDecisionAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AutomationDecisionReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutomationPending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("DerivedReleaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentificationState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IndexerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalisedTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PubDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SearchWasReason")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AutomationPending")
                        .HasFilter("\"AutomationPending\" = 1");

                    b.HasIndex("FirstSeenAt");

                    b.HasIndex("IdentificationState");

                    b.HasIndex("SiteId");

                    b.HasIndex("VideoId");

                    b.HasIndex("IndexerId", "DerivedReleaseId")
                        .IsUnique();

                    b.ToTable("release", null, t =>
                        {
                            t.HasCheckConstraint("CK_release_identification_state", "\"IdentificationState\" IN ('Unexamined','Unremarkable','Awaiting','Matched','SiteOnly','Ambiguous','Unknown')");
                        });

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.NotExported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.ReportedStateRow", b =>
                {
                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FulfilledAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFulfilled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Quality")
                        .HasColumnType("TEXT");

                    b.Property<string>("TerminalOutcome")
                        .HasColumnType("TEXT");

                    b.HasKey("VideoId", "UserHash");

                    b.ToTable("reported_state", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountStamped")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.Exported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.RoutineRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeferredUntil")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastDeferredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastDeferredReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFailureAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRunNowAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRunNowDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRunNowOutcome")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RunNowPending")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Lane", "DueAt");

                    b.HasIndex("Name", "Target")
                        .IsUnique();

                    b.ToTable("routine", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.NotExported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.RoutineRunRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemsHandled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResultsSeen")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoutineId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RowsAdded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId", "StartedAt");

                    b.ToTable("routine_run", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.NotExported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("session", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.NotExported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.VideoFileRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FiledPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LibraryEntryVideoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RuntimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoCodec")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryEntryVideoId");

                    b.HasIndex("OsHash");

                    b.ToTable("video_file", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountFree")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.Exported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.WantedVideoRow", b =>
                {
                    b.Property<long>("VideoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SinceAt")
                        .HasColumnType("TEXT");

                    b.HasKey("VideoId");

                    b.ToTable("wanted_video", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountScoped")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.NotExported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.WantedVideoSweepStateRow", b =>
                {
                    b.Property<long>("VideoId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IndexerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSearchedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("VideoId", "IndexerId");

                    b.HasIndex("IndexerId");

                    b.ToTable("wanted_video_sweep_state", (string)null);

                    b
                        .HasAnnotation("Fab:AccountClass", "AccountScoped")
                        .HasAnnotation("PrdbFab:ExportClass", ExportClass.NotExported);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.ArrivingFileCandidateRow", b =>
                {
                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.ArrivingFileRow", null)
                        .WithMany()
                        .HasForeignKey("ArrivingFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.AutomationRuleIndexerRow", b =>
                {
                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.AutomationRuleRow", "AutomationRule")
                        .WithMany()
                        .HasForeignKey("AutomationRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.IndexerRow", "Indexer")
                        .WithMany()
                        .HasForeignKey("IndexerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutomationRule");

                    b.Navigation("Indexer");
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.CatalogueImageRow", b =>
                {
                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.CatalogueVideoRow", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.CatalogueVideoActorRow", b =>
                {
                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.CatalogueActorRow", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.CatalogueVideoRow", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.CatalogueVideoPreNameRow", b =>
                {
                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.CatalogueVideoRow", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.CatalogueVideoRow", b =>
                {
                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.CatalogueSiteRow", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.DownloadOriginRuleRow", b =>
                {
                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.AutomationRuleRow", "AutomationRule")
                        .WithMany()
                        .HasForeignKey("AutomationRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.DownloadRow", "Download")
                        .WithMany()
                        .HasForeignKey("DownloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutomationRule");

                    b.Navigation("Download");
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.FavouriteActorRow", b =>
                {
                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.CatalogueActorRow", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.FavouriteSiteRow", b =>
                {
                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.CatalogueSiteRow", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.IndexerWalkStateRow", b =>
                {
                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.IndexerRow", "Indexer")
                        .WithOne()
                        .HasForeignKey("Prdb.Fab.Infrastructure.Persistence.IndexerWalkStateRow", "IndexerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indexer");
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.ReleaseCandidateRow", b =>
                {
                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.ReleaseRow", "Release")
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.CatalogueVideoRow", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.ReleaseRow", b =>
                {
                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.IndexerRow", "Indexer")
                        .WithMany()
                        .HasForeignKey("IndexerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.CatalogueSiteRow", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.CatalogueVideoRow", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Indexer");

                    b.Navigation("Site");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.RoutineRunRow", b =>
                {
                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.RoutineRow", "Routine")
                        .WithMany()
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.VideoFileRow", b =>
                {
                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.LibraryEntryRow", null)
                        .WithMany()
                        .HasForeignKey("LibraryEntryVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.WantedVideoRow", b =>
                {
                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.CatalogueVideoRow", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.WantedVideoSweepStateRow", b =>
                {
                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.IndexerRow", "Indexer")
                        .WithMany()
                        .HasForeignKey("IndexerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.WantedVideoRow", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indexer");

                    b.Navigation("Video");
                });
#pragma warning restore 612, 618
        }
    }
}
