// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prdb.Fab.Infrastructure.Persistence;

#nullable disable

namespace Prdb.Fab.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FabDbContext))]
    [Migration("20260827133615_TheGapsASkipLeavesBehind")]
    partial class TheGapsASkipLeavesBehind
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.IndexerRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastVerdict")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("indexer", (string)null);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.InstallationRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IndexersSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LibraryRoot")
                        .HasColumnType("TEXT");

                    b.Property<string>("OnboardingStep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathMappingFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathMappingTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrdbApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrdbUserHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("SabnzbdApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SabnzbdCategory")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SabnzbdSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SabnzbdUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("installation", null, t =>
                        {
                            t.HasCheckConstraint("CK_installation_one_row", "\"Id\" = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IndexersSkipped = false,
                            OnboardingStep = "Password",
                            SabnzbdSkipped = false
                        });
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.RoutineRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFailureAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Lane", "DueAt");

                    b.HasIndex("Name", "Target")
                        .IsUnique();

                    b.ToTable("routine", (string)null);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.RoutineRunRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemsHandled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<long>("RoutineId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId", "StartedAt");

                    b.ToTable("routine_run", (string)null);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.SkeletonItemRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SweptAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SweptAt");

                    b.ToTable("skeleton_item", (string)null);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.RoutineRunRow", b =>
                {
                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.RoutineRow", "Routine")
                        .WithMany()
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Routine");
                });
#pragma warning restore 612, 618
        }
    }
}
