// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prdb.Fab.Infrastructure.Persistence;

#nullable disable

namespace Prdb.Fab.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FabDbContext))]
    partial class FabDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.RoutineRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFailureAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Lane", "DueAt");

                    b.HasIndex("Name", "Target")
                        .IsUnique();

                    b.ToTable("routine", (string)null);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.RoutineRunRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemsHandled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<long>("RoutineId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId", "StartedAt");

                    b.ToTable("routine_run", (string)null);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.SkeletonItemRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SweptAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SweptAt");

                    b.ToTable("skeleton_item", (string)null);
                });

            modelBuilder.Entity("Prdb.Fab.Infrastructure.Persistence.RoutineRunRow", b =>
                {
                    b.HasOne("Prdb.Fab.Infrastructure.Persistence.RoutineRow", "Routine")
                        .WithMany()
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Routine");
                });
#pragma warning restore 612, 618
        }
    }
}
