namespace Prdb.Fab.Core.Sync;

/// <summary>
/// Where one request to publish previews of the existing Library stands
/// (ADR 0064).
/// </summary>
/// <remarks>
/// <para>
/// ADR 0064 puts the existing Library behind an explicit bounded request
/// precisely so that upgrading, enabling the switch or restoring a document
/// starts nothing. This is what such a request is while it lasts, and the four
/// members are the four things a person can have done to it.
/// </para>
/// <para>
/// <strong>None of them says anything about a publication.</strong> What became
/// of each preview the request selected is
/// <see cref="PreviewPublicationState"/>'s answer, on the row that carries it;
/// this says only whether more files are still being taken up. A request that
/// is <see cref="Finished"/> may well have uploads still in flight behind it.
/// </para>
/// </remarks>
public enum PreviewBackfillState
{
    /// <summary>
    /// Taking up eligible Library files, one per run of the generating routine.
    /// </summary>
    Running,

    /// <summary>
    /// Taking up nothing, and holding back what it has already taken up.
    /// </summary>
    /// <remarks>
    /// Nothing is given up: the rows this request selected stay exactly where
    /// they are, generated bytes included, and resuming lets them go on. What a
    /// pause is for is the machine rather than the decision — a decode is
    /// minutes of CPU, and somebody who wants it back has no other way to ask.
    /// </remarks>
    Paused,

    /// <summary>
    /// Ended by a person, with everything it had selected and not sent given
    /// up.
    /// </summary>
    /// <remarks>
    /// What cancelling can reach is what has not left: an intent, and a
    /// generated pair waiting for its upload. A submission prdb accepted stays
    /// at prdb — this tool has no retraction and ADR 0064 says so in those
    /// words — and an upload whose outcome nobody could establish stays the
    /// question it is, because cancelling a request is not an answer to it.
    /// </remarks>
    Cancelled,

    /// <summary>
    /// Ended on its own: every eligible Library file has been taken up.
    /// </summary>
    Finished,
}
